sniffy/sniffy

- README.md
- pom.xml
- src/main/java/com/github/bedrin/jdbc/sniffer/Spy.java
- src/test/groovy/com/github/bedrin/jdbc/sniffer/spock/QueryCounterSpec.groovy
SpockFramework support; part of [Support TestNG and other frameworks](https://github.com/bedrin/jdbc-sniffer/issues/14) story
> Added spock test

- src/main/java/com/github/bedrin/jdbc/sniffer/Sniffer.java
- src/main/java/com/github/bedrin/jdbc/sniffer/Spy.java
- src/main/java/com/github/bedrin/jdbc/sniffer/WrongNumberOfQueriesError.java
- src/main/java/com/github/bedrin/jdbc/sniffer/sql/StatementMetaData.java
- src/test/java/com/github/bedrin/jdbc/sniffer/SnifferListenersTest.java
https://github.com/bedrin/jdbc-sniffer/issues/43
> Store executed queries together with calling thread in Spy instances

- src/main/java/com/github/bedrin/jdbc/sniffer/servlet/BufferedServletOutputStream.java
- src/main/java/com/github/bedrin/jdbc/sniffer/servlet/BufferedServletResponseWrapper.java
- src/main/java/com/github/bedrin/jdbc/sniffer/servlet/FlushResponseListener.java
- src/main/java/com/github/bedrin/jdbc/sniffer/servlet/SnifferFilter.java
- src/test/java/com/github/bedrin/jdbc/sniffer/servlet/SnifferFilterTest.java
Even for responses with content type of "text/html" use mime magic to check if it is not XML
> Do not inject sniffer to XML documents

- src/main/java/com/github/bedrin/jdbc/sniffer/servlet/SnifferServlet.java
- src/main/java/com/github/bedrin/jdbc/sniffer/util/StringUtil.java
- src/test/java/com/github/bedrin/jdbc/sniffer/servlet/SnifferServletTest.java
- src/test/java/com/github/bedrin/jdbc/sniffer/util/StringUtilTest.java
https://github.com/bedrin/jdbc-sniffer/issues/72
> Escape JSON strings

- src/main/java/io/sniffy/servlet/BufferedServletResponseWrapper.java
- src/test/java/io/sniffy/servlet/SnifferFilterTest.java
https://github.com/sniffy/sniffy/issues/99
> Parse Content-Length header

- src/main/java/io/sniffy/Spy.java
- src/main/java/io/sniffy/WrongNumberOfQueriesError.java
- src/test/java/io/sniffy/SnifferListenersTest.java
Fix for https://github.com/sniffy/sniffy/issues/130
> WrongNumberOfQueriesError doesn't contain information about query type

- pom.xml
- sniffy-core/pom.xml
- sniffy-core/src/main/java/io/sniffy/servlet/BufferedServletOutputStream.java
- sniffy-core/src/main/java/io/sniffy/servlet/BufferedServletResponseWrapper.java
- sniffy-core/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
- sniffy-core/src/test/java/io/sniffy/servlet/SnifferFilterTest.java
https://github.com/sniffy/sniffy/issues/184
> Servlet 3.1 support

- sniffy-core/src/main/java/io/sniffy/servlet/BufferedPrintWriter.java
- sniffy-core/src/main/java/io/sniffy/servlet/BufferedServletResponseWrapper.java
- sniffy-core/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
- sniffy-core/src/test/java/io/sniffy/servlet/SnifferFilterTest.java
Fix for https://github.com/sniffy/sniffy/issues/183
> issues/183: Sniffy breaks character encoding

- sniffy-core/src/main/java/io/sniffy/sql/SniffyDataSource.java
- sniffy-core/src/test/java/io/sniffy/sql/SniffyDataSourceTest.java
https://github.com/sniffy/sniffy/issues/185
> issues/185: DataSource wrapper implementation

- pom.xml
- sniffy-core/src/main/java/io/sniffy/servlet/SnifferFilter.java
- sniffy-core/src/main/java/io/sniffy/servlet/SnifferServlet.java
- sniffy-core/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
https://github.com/sniffy/sniffy/issues/191
> issues/191: X-Request-Details contains absolute URLs

- sniffy-core/src/main/java/io/sniffy/servlet/SnifferFilter.java
- sniffy-core/src/test/java/io/sniffy/servlet/SnifferFilterTest.java
Closed https://github.com/sniffy/sniffy/issues/205
> Fixed NPE when filter is not initialized (Spring)

- sniffy-core/src/main/java/io/sniffy/sql/SniffyDriver.java
- sniffy-core/src/test/java/io/sniffy/BaseTest.java
- sniffy-core/src/test/java/io/sniffy/sql/SniffyDriverTest.java
- sniffy-core/src/test/java/io/sniffy/sql/TestDriver.java
Closes https://github.com/sniffy/sniffy/issues/204
> Fixed NPE in SniffyDriver.connect() method

- sniffy-core/src/main/java/io/sniffy/Sniffy.java
- sniffy-core/src/test/java/io/sniffy/SniffyTest.java
Closes https://github.com/sniffy/sniffy/issues/214
> Fixed IndexOutOfBoundsException caused by concurrency issues

- sniffy-core/src/main/java/io/sniffy/servlet/SnifferFilter.java
- sniffy-core/src/main/java/io/sniffy/servlet/SnifferServlet.java
- sniffy-core/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
- sniffy-core/src/test/java/io/sniffy/servlet/SnifferFilterTest.java
- sniffy-core/src/test/java/io/sniffy/servlet/SnifferServletTest.java
Fix for https://github.com/sniffy/sniffy/issues/228
> issues/228: Sniffy doesn't work for some URL's

- sniffy-core/src/main/java/io/sniffy/servlet/SnifferServlet.java
- sniffy-core/src/test/java/io/sniffy/servlet/SnifferServletTest.java
Fixes https://github.com/sniffy/sniffy/issues/173
> issues/173: Time units are inconsistent

- sniffy-core/src/main/java/io/sniffy/registry/ConnectionsRegistry.java
- sniffy-core/src/main/java/io/sniffy/registry/ConnectionsRegistryStorage.java
- sniffy-core/src/main/java/io/sniffy/servlet/SnifferFilter.java
- sniffy-core/src/test/java/io/sniffy/servlet/SnifferFilterTest.java
Implements https://github.com/sniffy/sniffy/issues/180
> issues/180: per-user fault tolerance simulations

- sniffy-core/src/main/java/io/sniffy/servlet/SnifferFilter.java
- sniffy-core/src/main/java/io/sniffy/servlet/SnifferServlet.java
- sniffy-core/src/main/java/io/sniffy/util/IOUtil.java
Fixes https://github.com/sniffy/sniffy/issues/232
> Add CORS headers to Sniffy responses

- README.md
- sniffy-core/src/main/java/io/sniffy/servlet/SniffyFilter.java
Fix for https://github.com/sniffy/sniffy/issues/200
> Renamed X- headers to Sniffy- headers

- sniffy-core/src/main/java/io/sniffy/servlet/SniffyServlet.java
- sniffy-core/src/test/java/io/sniffy/servlet/SniffyServletTest.java
Fix for https://github.com/sniffy/sniffy/issues/245
> issues/245 Cannot disable/enable datasource with slash in connection URL

- sniffy-web/pom.xml
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyFilter.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyServlet.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyFilterTest.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyServletTest.java
Fix for https://github.com/sniffy/sniffy/issues/213
> issues/213: JS Map does not work

- sniffy/pom.xml
Fixes https://github.com/sniffy/sniffy/issues/267
> issues/267: Sniffy uber jar doesn't come with sources in maven central

- sniffy-web/src/main/java/io/sniffy/boot/SniffySpringConfiguration.java
- sniffy-web/src/main/java/io/sniffy/servlet/BufferedServletResponseWrapper.java
- sniffy-web/src/main/java/io/sniffy/servlet/RequestStats.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyFilter.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyFilterTest.java
Fix for https://github.com/sniffy/sniffy/issues/260
> issues/260 Error pages are missing Sniffy

- pom.xml
- sniffy-integration-tests/sniffy-integration-tests-spring-boot/src/main/java/io/sniffy/test/boot/TestController.java
- sniffy-integration-tests/sniffy-integration-tests-spring-boot/src/main/resources/static/error.html
- sniffy-integration-tests/sniffy-integration-tests-spring-boot/src/test/main/java/io/sniffy/test/boot/TestApplicationTest.java
- sniffy-web/pom.xml
- sniffy-web/src/main/java/io/sniffy/servlet/RequestStats.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyServlet.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyServletTest.java
Fix for https://github.com/sniffy/sniffy/issues/280
> issues/280 Show exceptions raised on server side

- sniffy-core/src/main/java/io/sniffy/configuration/SniffyConfiguration.java
- sniffy-core/src/test/java/io/sniffy/configuration/SniffyConfigurationTest.java
- sniffy-documentation/src/main/asciidoc/migration-to-3.1.adoc
- sniffy-documentation/src/main/asciidoc/setup-filter.adoc
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyFilter.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyFilterConfigurationTest.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyFilterTest.java
Fixes https://github.com/sniffy/sniffy/issues/288
> Support "system" value in SniffyFilter configuration

- sniffy-web/src/main/java/io/sniffy/servlet/BufferedServletResponseWrapper.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyFilterTest.java
Fixes https://github.com/sniffy/sniffy/issues/290
> issues/290 Parse Content-Type from setHeader/addHeader methods

- .gitignore
- sniffy-core/src/main/resources/META-INF/services/java.sql.Driver
- sniffy-documentation/src/main/asciidoc/index.adoc
- sniffy-documentation/src/main/asciidoc/setup-containers.adoc
- sniffy-documentation/src/main/asciidoc/setup-filter.adoc
- sniffy/pom.xml
- sniffy/src/jboss-module/module.xml
- sniffy/src/jboss-module/sniffy-jboss-module.xml
Implements https://github.com/sniffy/sniffy/issues/291
> issues/291 Produce JBoss module / update documentation

- pom.xml
- sniffy-core/pom.xml
- sniffy-core/src/main/java/io/sniffy/Sniffy.java
- sniffy-core/src/main/java/io/sniffy/configuration/SniffyConfiguration.java
- sniffy-core/src/main/java/io/sniffy/sql/SqlUtil.java
- sniffy-core/src/main/java/io/sniffy/sql/StatementInvocationHandler.java
- sniffy-core/src/main/java/io/sniffy/sql/StatementMetaData.java
- sniffy-core/src/test/java/io/sniffy/SniffyTest.java
- sniffy-core/src/test/java/io/sniffy/configuration/SniffyConfigurationTest.java
- sniffy-core/src/test/java/io/sniffy/sql/QueryTest.java
- sniffy-core/src/test/java/io/sniffy/sql/SqlUtilTest.java
- sniffy-documentation/src/main/asciidoc/configuration.adoc
- sniffy-web/src/main/java/io/sniffy/boot/EnableSniffy.java
- sniffy-web/src/main/java/io/sniffy/boot/SniffySpringConfiguration.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyServlet.java
- sniffy-web/src/test/java/io/sniffy/boot/EnableSniffyTest.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyServletTest.java
- sniffy/pom.xml
Implements https://github.com/sniffy/sniffy/issues/292
> issues/292 Calculate Top slowest queries across all requests

- sniffy-web/src/main/java/io/sniffy/servlet/RequestStats.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
Fixes https://github.com/sniffy/sniffy/issues/300
> issues/300 Sniffy shows response time with leading zeroes

- sniffy-core/src/main/java/io/sniffy/registry/ConnectionsRegistry.java
- sniffy-core/src/test/java/io/sniffy/registry/ConnectionsRegistryTest.java
Fixes https://github.com/sniffy/sniffy/issues/302
> issues/302 Backslashes are not escaped in connection registry

- sniffy-core/src/main/java/io/sniffy/configuration/SniffyConfiguration.java
- sniffy-core/src/test/java/io/sniffy/configuration/SniffyConfigurationTest.java
- sniffy-documentation/src/main/asciidoc/configuration.adoc
- sniffy-documentation/src/main/asciidoc/setup-filter.adoc
- sniffy-web/src/main/java/io/sniffy/boot/EnableSniffy.java
- sniffy-web/src/main/java/io/sniffy/boot/SniffyAdvancedConfiguration.java
- sniffy-web/src/main/java/io/sniffy/boot/SniffySpringConfiguration.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyFilter.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
- sniffy-web/src/test/java/io/sniffy/boot/EnableSniffyTest.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyFilterTest.java
Fixes https://github.com/sniffy/sniffy/issues/304
> Introduce injectHtmlExcludePattern configuration property

- sniffy-integration-tests/pom.xml
- sniffy-integration-tests/sniffy-integration-test-tomcat/pom.xml
- sniffy-integration-tests/sniffy-integration-test-tomcat/src/main/java/io/sniffy/test/tomcat/IntegrationTestServlet.java
- sniffy-integration-tests/sniffy-integration-test-tomcat/src/main/java/io/sniffy/test/tomcat/SniffyAnnotationFilter.java
- sniffy-integration-tests/sniffy-integration-test-tomcat/src/test/java/io/sniffy/test/tomcat/BaseTomcatIT.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
Fixes https://github.com/sniffy/sniffy/issues/319
> issues/319 Sniffy is injected incorrectly to pages with query parameters

- sniffy-integration-tests/sniffy-integration-test-tomcat/src/main/java/io/sniffy/test/tomcat/IntegrationTestServlet.java
- sniffy-integration-tests/sniffy-integration-test-tomcat/src/test/java/io/sniffy/test/tomcat/BaseTomcatIT.java
- sniffy-web/src/main/java/io/sniffy/servlet/HtmlInjector.java
- sniffy-web/src/test/java/io/sniffy/servlet/HtmlInjectorTest.java
Fixes https://github.com/sniffy/sniffy/issues/321
> issues/321 Sniffy doesn't work with base tag

- sniffy-core/src/test/java/io/sniffy/socket/EchoServerRule.java
- sniffy-documentation/src/main/asciidoc/index.adoc
- sniffy-documentation/src/main/asciidoc/test-junit.adoc
- sniffy-documentation/src/main/asciidoc/test-spring.adoc
- sniffy-documentation/src/main/asciidoc/test-testng.adoc
- sniffy-test/sniffy-junit/src/main/java/io/sniffy/test/junit/SniffyRule.java
- sniffy-test/sniffy-junit/src/test/java/io/sniffy/test/junit/DisableSocketsTest.java
- sniffy-test/sniffy-junit/src/test/java/io/sniffy/test/junit/usage/DisableConnectivityOverviewTest.java
- sniffy-test/sniffy-junit/src/test/java/io/sniffy/test/junit/usage/JUnitUsageTest.java
- sniffy-test/sniffy-spring-test/src/main/java/io/sniffy/test/spring/SniffySpringTestListener.java
- sniffy-test/sniffy-spring-test/src/test/java/io/sniffy/test/spring/SpringDisableSocketsTest.java
- sniffy-test/sniffy-spring-test/src/test/java/io/sniffy/test/spring/usage/SpringUsageTest.java
- sniffy-test/sniffy-test-common/src/main/java/io/sniffy/socket/DisableSockets.java
- sniffy-test/sniffy-test-common/src/main/java/io/sniffy/test/AnnotationProcessor.java
- sniffy-test/sniffy-test-common/src/test/java/io/sniffy/test/AnnotationProcessorTest.java
- sniffy-test/sniffy-testng/src/main/java/io/sniffy/test/testng/SniffyTestNgListener.java
- sniffy-test/sniffy-testng/src/test/java/io/sniffy/test/testng/DisableSocketsTestNg.java
- sniffy-test/sniffy-testng/src/test/java/io/sniffy/test/testng/usage/UsageTestNg.java
Fixes https://github.com/sniffy/sniffy/issues/242 and https://github.com/sniffy/sniffy/issues/224
> @DisableSockets annotation support

- pom.xml
Fixes https://github.com/sniffy/sniffy/issues/310
> issues/310 webjar isn't added to shaded sources jar

- sniffy-core/src/main/java/io/sniffy/socket/SnifferInputStream.java
- sniffy-core/src/main/java/io/sniffy/socket/SnifferOutputStream.java
- sniffy-core/src/main/java/io/sniffy/socket/SnifferSocketImpl.java
- sniffy-core/src/test/java/io/sniffy/registry/ConnectionsRegistryTest.java
- sniffy-core/src/test/java/io/sniffy/socket/SnifferOutputStreamTest.java
- sniffy-core/src/test/java/io/sniffy/socket/SnifferSocketImplTest.java
- sniffy-core/src/test/java/io/sniffy/sql/SniffyDriverTest.java
- sniffy-documentation/src/main/asciidoc/index.adoc
- sniffy-documentation/src/main/asciidoc/network-issues.adoc
Implements https://github.com/sniffy/sniffy/issues/340
> Use heuristics for adding delays to TCP connections

- sniffy-core/src/main/java/io/sniffy/sql/SqlStats.java
- sniffy-core/src/main/java/io/sniffy/sql/StatementInvocationHandler.java
- sniffy-core/src/test/java/io/sniffy/sql/PreparedStatementInvocationHandlerTest.java
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyServlet.java
Fixes https://github.com/sniffy/sniffy/issues/337
> issues/337: executeBatch might return negative number of affected rows

- sniffy-web/src/main/java/io/sniffy/servlet/SniffyServlet.java
- sniffy-web/src/test/java/io/sniffy/servlet/SniffyServletTest.java
- sniffy/src/main/java/io/sniffy/SniffyAgent.java
- sniffy/src/test/java/io/sniffy/SniffyAgentTest.java
https://github.com/sniffy/sniffy/issues/357 Sniffy extension doesn't work for CORS requests #357
> issues/357 Sniffy extension doesn't work for CORS requests #357

- sniffy-integration-tests/sniffy-integration-test-tomcat/pom.xml
- sniffy-web/src/main/java/io/sniffy/servlet/SniffyRequestProcessor.java
No request method and response code shown for main non-AJAX request
> https://github.com/sniffy/sniffy/issues/388

- .github/workflows/deploy.yml
- .github/workflows/pr.yml
- pom.xml
- sniffy-compatibility-tests/pom.xml
- sniffy-core/src/main/java/io/sniffy/socket/SnifferSocketImplFactory.java
- sniffy-core/src/main/java/io/sniffy/util/JVMUtil.java
- sniffy-core/src/main/java/io/sniffy/util/ReflectionFieldCopier.java
- sniffy-core/src/main/java/io/sniffy/util/ReflectionUtil.java
- sniffy-core/src/test/java/io/sniffy/configuration/SniffyConfigurationTest.java
- sniffy-core/src/test/java/io/sniffy/registry/ConnectionsRegistryTest.java
- sniffy-integration-tests/sniffy-integration-test-tomcat/pom.xml
- sniffy-module-nio-compat-deps/src/main/java-compat/java/nio/PublicSelChImpl.java
- sniffy-module-nio/src/main/java/io/sniffy/nio/SniffyAsynchronousChannelProvider.java
- sniffy-module-nio/src/main/java/io/sniffy/nio/SniffySelectorProviderModule.java
- sniffy-module-nio/src/test/java/io/sniffy/nio/Nio2SniffySocketTest.java
- sniffy-module-nio/src/test/java/io/sniffy/nio/NioSniffySocketTest.java
It would fail due to https://openjdk.java.net/jeps/396
> Test on Java 16 and 17
